package id.go.bkn.template.entities;

// Generated 06 Nov 14 12:06:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KewenanganUser generated by hbm2java
 */
@Entity
@Table(name = "kewenangan_user", catalog = "simwasdal")
public class KewenanganUser implements java.io.Serializable {

	private String loginId;
	private String tahunAudit;
	private String kewenanganDetailId;
	private String instansiId;

	public KewenanganUser() {
	}

	public KewenanganUser(String loginId, String tahunAudit,
			String kewenanganDetailId, String instansiId) {
		this.loginId = loginId;
		this.tahunAudit = tahunAudit;
		this.kewenanganDetailId = kewenanganDetailId;
		this.instansiId = instansiId;
	}

	@Id
	@Column(name = "LOGIN_ID", unique = true, nullable = false, length = 32)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "TAHUN_AUDIT", nullable = false, length = 4)
	public String getTahunAudit() {
		return this.tahunAudit;
	}

	public void setTahunAudit(String tahunAudit) {
		this.tahunAudit = tahunAudit;
	}

	@Column(name = "KEWENANGAN_DETAIL_ID", nullable = false, length = 32)
	public String getKewenanganDetailId() {
		return this.kewenanganDetailId;
	}

	public void setKewenanganDetailId(String kewenanganDetailId) {
		this.kewenanganDetailId = kewenanganDetailId;
	}

	@Column(name = "INSTANSI_ID", nullable = false, length = 32)
	public String getInstansiId() {
		return this.instansiId;
	}

	public void setInstansiId(String instansiId) {
		this.instansiId = instansiId;
	}

}
