package id.go.bkn.template.entities;

// Generated 06 Nov 14 10:38:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PnsElemenAudit generated by hbm2java
 */
@Entity
@Table(name = "pns_elemen_audit", catalog = "simwasdal")
public class PnsElemenAudit implements java.io.Serializable {

	private String id;
	private Login login;
	private String nama;
	private Date createDate;
	private String status;
	private String tahunAwalBerlaku;
	private String tahunAkhirBerlaku;
	private String noUrut;
	private String pnsAtasanElemenId;
	private Set<PnsKriteriaAudit> pnsKriteriaAudits = new HashSet<PnsKriteriaAudit>(
			0);

	public PnsElemenAudit() {
	}

	public PnsElemenAudit(String id, Login login, String nama, Date createDate,
			String status, String tahunAwalBerlaku, String tahunAkhirBerlaku,
			String noUrut) {
		this.id = id;
		this.login = login;
		this.nama = nama;
		this.createDate = createDate;
		this.status = status;
		this.tahunAwalBerlaku = tahunAwalBerlaku;
		this.tahunAkhirBerlaku = tahunAkhirBerlaku;
		this.noUrut = noUrut;
	}

	public PnsElemenAudit(String id, Login login, String nama, Date createDate,
			String status, String tahunAwalBerlaku, String tahunAkhirBerlaku,
			String noUrut, String pnsAtasanElemenId,
			Set<PnsKriteriaAudit> pnsKriteriaAudits) {
		this.id = id;
		this.login = login;
		this.nama = nama;
		this.createDate = createDate;
		this.status = status;
		this.tahunAwalBerlaku = tahunAwalBerlaku;
		this.tahunAkhirBerlaku = tahunAkhirBerlaku;
		this.noUrut = noUrut;
		this.pnsAtasanElemenId = pnsAtasanElemenId;
		this.pnsKriteriaAudits = pnsKriteriaAudits;
	}

	@Id
	@GeneratedValue()
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGIN_ID_CREATE", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "NAMA", nullable = false, length = 150)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TAHUN_AWAL_BERLAKU", nullable = false, length = 4)
	public String getTahunAwalBerlaku() {
		return this.tahunAwalBerlaku;
	}

	public void setTahunAwalBerlaku(String tahunAwalBerlaku) {
		this.tahunAwalBerlaku = tahunAwalBerlaku;
	}

	@Column(name = "TAHUN_AKHIR_BERLAKU", nullable = false, length = 4)
	public String getTahunAkhirBerlaku() {
		return this.tahunAkhirBerlaku;
	}

	public void setTahunAkhirBerlaku(String tahunAkhirBerlaku) {
		this.tahunAkhirBerlaku = tahunAkhirBerlaku;
	}

	@Column(name = "NO_URUT", nullable = false, length = 2)
	public String getNoUrut() {
		return this.noUrut;
	}

	public void setNoUrut(String noUrut) {
		this.noUrut = noUrut;
	}

	@Column(name = "PNS_ATASAN_ELEMEN_ID", length = 32)
	public String getPnsAtasanElemenId() {
		return this.pnsAtasanElemenId;
	}

	public void setPnsAtasanElemenId(String pnsAtasanElemenId) {
		this.pnsAtasanElemenId = pnsAtasanElemenId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnsElemenAudit")
	public Set<PnsKriteriaAudit> getPnsKriteriaAudits() {
		return this.pnsKriteriaAudits;
	}

	public void setPnsKriteriaAudits(Set<PnsKriteriaAudit> pnsKriteriaAudits) {
		this.pnsKriteriaAudits = pnsKriteriaAudits;
	}

}
