package id.go.bkn.template.entities;

// Generated 06 Nov 14 10:38:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * PnsTransaksiJawaban generated by hbm2java
 */
@Entity
@Table(name = "pns_transaksi_jawaban", catalog = "simwasdal")
public class PnsTransaksiJawaban implements java.io.Serializable {

	private String id;
	private PnsKriteriaAudit pnsKriteriaAudit;
	private String tahunAudit;
	private String instansiId;
	private String valueKriteriaAudit;
	private String ketValueKriteriaAudit;
	private byte[] buktiAudit;
	private short skorAudit;
	private String keterangan;
	private String isiLoginId;
	private Date isiUpdateDate;
	private String auditLoginId;
	private Date auditUpdateDate;
	private String buktiAuditValue;

	public PnsTransaksiJawaban() {
	}

	public PnsTransaksiJawaban(String id, PnsKriteriaAudit pnsKriteriaAudit,
			String tahunAudit, String instansiId, String valueKriteriaAudit,
			String ketValueKriteriaAudit, byte[] buktiAudit, short skorAudit,
			String keterangan, String isiLoginId, Date isiUpdateDate,
			String auditLoginId, Date auditUpdateDate) {
		this.id = id;
		this.pnsKriteriaAudit = pnsKriteriaAudit;
		this.tahunAudit = tahunAudit;
		this.instansiId = instansiId;
		this.valueKriteriaAudit = valueKriteriaAudit;
		this.ketValueKriteriaAudit = ketValueKriteriaAudit;
		this.buktiAudit = buktiAudit;
		this.skorAudit = skorAudit;
		this.keterangan = keterangan;
		this.isiLoginId = isiLoginId;
		this.isiUpdateDate = isiUpdateDate;
		this.auditLoginId = auditLoginId;
		this.auditUpdateDate = auditUpdateDate;
	}

	public PnsTransaksiJawaban(String id, PnsKriteriaAudit pnsKriteriaAudit,
			String tahunAudit, String instansiId, String valueKriteriaAudit,
			String ketValueKriteriaAudit, byte[] buktiAudit, short skorAudit,
			String keterangan, String isiLoginId, Date isiUpdateDate,
			String auditLoginId, Date auditUpdateDate, String buktiAuditValue) {
		this.id = id;
		this.pnsKriteriaAudit = pnsKriteriaAudit;
		this.tahunAudit = tahunAudit;
		this.instansiId = instansiId;
		this.valueKriteriaAudit = valueKriteriaAudit;
		this.ketValueKriteriaAudit = ketValueKriteriaAudit;
		this.buktiAudit = buktiAudit;
		this.skorAudit = skorAudit;
		this.keterangan = keterangan;
		this.isiLoginId = isiLoginId;
		this.isiUpdateDate = isiUpdateDate;
		this.auditLoginId = auditLoginId;
		this.auditUpdateDate = auditUpdateDate;
		this.buktiAuditValue = buktiAuditValue;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KRITERIA_AUDIT_ID", nullable = false)
	public PnsKriteriaAudit getPnsKriteriaAudit() {
		return this.pnsKriteriaAudit;
	}

	public void setPnsKriteriaAudit(PnsKriteriaAudit pnsKriteriaAudit) {
		this.pnsKriteriaAudit = pnsKriteriaAudit;
	}

	@Column(name = "TAHUN_AUDIT", nullable = true, length = 4)
	public String getTahunAudit() {
		return this.tahunAudit;
	}

	public void setTahunAudit(String tahunAudit) {
		this.tahunAudit = tahunAudit;
	}

	@Column(name = "INSTANSI_ID", nullable = false, length = 32)
	public String getInstansiId() {
		return this.instansiId;
	}

	public void setInstansiId(String instansiId) {
		this.instansiId = instansiId;
	}

	@Column(name = "VALUE_KRITERIA_AUDIT", nullable = true, length = 1)
	public String getValueKriteriaAudit() {
		return this.valueKriteriaAudit;
	}

	public void setValueKriteriaAudit(String valueKriteriaAudit) {
		this.valueKriteriaAudit = valueKriteriaAudit;
	}

	@Column(name = "KET_VALUE_KRITERIA_AUDIT", nullable = true, length = 16777215)
	public String getKetValueKriteriaAudit() {
		return this.ketValueKriteriaAudit;
	}

	public void setKetValueKriteriaAudit(String ketValueKriteriaAudit) {
		this.ketValueKriteriaAudit = ketValueKriteriaAudit;
	}

	@Column(name = "BUKTI_AUDIT", nullable = true)
	public byte[] getBuktiAudit() {
		return this.buktiAudit;
	}

	public void setBuktiAudit(byte[] buktiAudit) {
		this.buktiAudit = buktiAudit;
	}

	@Column(name = "SKOR_AUDIT", nullable = true)
	public short getSkorAudit() {
		return this.skorAudit;
	}

	public void setSkorAudit(short skorAudit) {
		this.skorAudit = skorAudit;
	}

	@Column(name = "KETERANGAN", nullable = true, length = 16777215)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@Column(name = "ISI_LOGIN_ID", nullable = true, length = 32)
	public String getIsiLoginId() {
		return this.isiLoginId;
	}

	public void setIsiLoginId(String isiLoginId) {
		this.isiLoginId = isiLoginId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ISI_UPDATE_DATE", nullable = false, length = 19)
	public Date getIsiUpdateDate() {
		return this.isiUpdateDate;
	}

	public void setIsiUpdateDate(Date isiUpdateDate) {
		this.isiUpdateDate = isiUpdateDate;
	}

	@Column(name = "AUDIT_LOGIN_ID", nullable = false, length = 32)
	public String getAuditLoginId() {
		return this.auditLoginId;
	}

	public void setAuditLoginId(String auditLoginId) {
		this.auditLoginId = auditLoginId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_UPDATE_DATE", nullable = false, length = 19)
	public Date getAuditUpdateDate() {
		return this.auditUpdateDate;
	}

	public void setAuditUpdateDate(Date auditUpdateDate) {
		this.auditUpdateDate = auditUpdateDate;
	}

	@Column(name = "BUKTI_AUDIT_VALUE", length = 1)
	public String getBuktiAuditValue() {
		return this.buktiAuditValue;
	}

	public void setBuktiAuditValue(String buktiAuditValue) {
		this.buktiAuditValue = buktiAuditValue;
	}

}
