package id.go.bkn.template.entities;

// Generated 06 Nov 14 10:38:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instansi generated by hbm2java
 */
@Entity
@Table(name = "instansi", catalog = "simwasdal")
public class Instansi implements java.io.Serializable {

	private String id;
	private String nama;
	private String cepatKode;
	private Set<Login> logins = new HashSet<Login>(0);

	public Instansi() {
	}

	public Instansi(String id, String nama) {
		this.id = id;
		this.nama = nama;
	}

	public Instansi(String id, String nama, String cepatKode, Set<Login> logins) {
		this.id = id;
		this.nama = nama;
		this.cepatKode = cepatKode;
		this.logins = logins;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAMA", nullable = false, length = 150)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "CEPAT_KODE", length = 4)
	public String getCepatKode() {
		return this.cepatKode;
	}

	public void setCepatKode(String cepatKode) {
		this.cepatKode = cepatKode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instansi")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

}
